window.SPARI_CONFIG = {
  API_URL: "PASTE_URL_APPS_SCRIPT_DI_SINI",
  APP_TITLE: "SPARI HUT RI KE-81",
  ORGANIZATION: "Serikat Pekerja AEON Retail Indonesia",
  BANK: "CIMB",
  ACCOUNT_NUMBER: "707503937600",
  ACCOUNT_NAME: "Ahmad Faiz"
};
